CREATE TABLE projects(
    project_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    project_name VARCHAR2(500 CHAR),
    project_description VARCHAR2(1000 CHAR),
    PRIMARY KEY(project_id)
);

CREATE TABLE project_columns(
    column_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    column_name VARCHAR2(255 CHAR) UNIQUE,
    column_status VARCHAR2(255 CHAR) UNIQUE,
    column_listPos NUMBER,
    project_id NUMBER,
    PRIMARY KEY(column_id)
);

CREATE TABLE tasks(
    task_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    task_name VARCHAR2(500 CHAR),
    task_description VARCHAR2(5000 CHAR),
    task_priority NUMBER UNIQUE,
    column_id NUMBER,
    PRIMARY KEY(task_id)
);

CREATE TABLE comments(
    comment_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    comment_text VARCHAR2(5000 CHAR),
    comment_creation TIMESTAMP,
    task_id NUMBER,
    PRIMARY KEY(comment_id)
);
COMMIT;







